# ============================================================
#  file:       dbt/dbt_project.yml
#  purpose:    dbt project config: staging views, star and snowflake mart tables
#  owner:      Luke Udell
#  spdx:       MIT
#  std:        [STD-04]
#  adr:        none
#  ticket:     none
#  ticket-url: none
#  created:    2026-07-19
# ============================================================
name: 'andvari'
version: '0.1.0'
config-version: 2

profile: 'andvari'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  andvari:
    staging:
      +materialized: view
      +schema: staging
    marts:
      star:
        +materialized: table
        +schema: star
      snowflake:
        +materialized: table
        +schema: snowflake
